- build.gradle
- gradle/version.properties
- src/main/java/io/crate/jmx/Agent.java
- src/main/java/io/crate/jmx/CrateCollector.java
- src/main/java/io/crate/jmx/MBeanPropertyCache.java
- src/main/java/io/crate/jmx/http/HttpReadyHandler.java
log4j is requiring a configuration which won’t be available yet at Crate
when the agent is starting.
also removes debug related loggings.
> removes log4j dependency, use internal logging instead

- CONTRIBUTING.rst
- DEVELOPMENT.rst
- README.rst
- build.gradle
- src/main/java/io/crate/jmx/Agent.java
- src/main/java/io/crate/jmx/CrateCollector.java
- src/main/java/io/crate/jmx/recorder/MetricSampleConsumer.java
- src/main/java/io/crate/jmx/recorder/NodeStatus.java
- src/main/java/io/crate/jmx/recorder/QueryStats.java
- src/main/java/io/crate/jmx/recorder/Recorder.java
- src/main/java/io/crate/jmx/recorder/RecorderRegistry.java
- src/test/java/io/crate/jmx/CrateCollectorTest.java
- src/test/java/io/crate/jmx/integrationtests/AbstractITest.java
- src/test/java/io/crate/jmx/integrationtests/MetricsITest.java
This makes it possible to have better metric names and labels, unknown crate metrics will use a default sample recorder.
Example output:
```
crate_ready 1.0
crate_queries{query="Select",} 0.0
crate_queries{query="Insert",} 0.0
crate_queries{query="Update",} 0.0
crate_queries{query="Delete",} 0.0
crate_queries{query="Overall",} 1.2254901960784315
crate_query_duration_seconds{query="Select",} 0.0
crate_query_duration_seconds{query="Insert",} 0.0
crate_query_duration_seconds{query="Update",} 0.0
crate_query_duration_seconds{query="Delete",} 0.0
crate_query_duration_seconds{query="Overall",} 0.0
```
Additionally some smaller cleanups were made, see commits.
>  adds custom metric recorder for every known crate mbean

- CHANGES.rst
- src/main/java/io/crate/jmx/CrateCollector.java
- src/test/java/io/crate/jmx/integrationtests/MetricsITest.java
collect() will always collect all found metrics everytime, 
so the map must be cleared before.
otherwise the same metric samples will be stored and responded multiple
times.
> clear the existing metrics map before collecting

- CHANGES.rst
- src/main/java/io/crate/jmx/CrateCollector.java
- src/main/java/io/crate/jmx/recorder/Recorder.java
- src/main/java/io/crate/jmx/recorder/RecorderRegistry.java
- src/main/java/io/crate/jmx/recorder/ThreadPools.java
- src/test/java/io/crate/jmx/CrateCollectorTest.java
- src/test/java/io/crate/jmx/integrationtests/AbstractITest.java
- src/test/java/io/crate/jmx/integrationtests/MetricsITest.java
The included integration test will only succeed if the latest nightly contains the `ThreadPools` JMX MXBean, see https://github.com/crate/crate/pull/7532.
Also the `LATEST` uri defined at the intergation test suite must be updated to point to the latest nightly.
> add support for CrateDB’s `ThreadPools` MXBean

- CHANGES.rst
- src/main/java/io/crate/jmx/recorder/CircuitBreakers.java
- src/main/java/io/crate/jmx/recorder/RecorderRegistry.java
- src/test/java/io/crate/jmx/CrateCollectorTest.java
- src/test/java/io/crate/jmx/integrationtests/AbstractITest.java
- src/test/java/io/crate/jmx/integrationtests/MetricsITest.java
integration tests will only pass after https://github.com/crate/crate/pull/7578 is included at the latest nightly and the nightly URI is updated. so do not merge yet.
> add support for the `CircuitBreakers` MXBean

- CHANGES.rst
- src/main/java/io/crate/jmx/CrateCollector.java
- src/main/java/io/crate/jmx/recorder/CircuitBreakers.java
- src/main/java/io/crate/jmx/recorder/Recorder.java
- src/main/java/io/crate/jmx/recorder/ThreadPools.java
- src/test/java/io/crate/jmx/CrateCollectorTest.java
These attributes are ignored by intend and should not result
in SERVE log entries.
Follow up of https://github.com/crate/jmx_exporter/commit/d306eff1c414f77e16507282278a10a1980678c2
> Don’t log ignored NodeInfo MBean string attributes

- README.rst
the diff is messy because I reordered the links (alphabetical)
> improve help section

- src/test/java/io/crate/jmx/integrationtests/MetricsITest.java
> Fix testCircuitBreakersMetrics

- CHANGES.rst
- src/main/java/io/crate/jmx/CrateCollector.java
- src/main/java/io/crate/jmx/recorder/NodeInfo.java
- src/main/java/io/crate/jmx/recorder/Recorder.java
- src/test/java/io/crate/jmx/CrateCollectorTest.java
This adds the following shard specific metrices:
```
crate_node(name=shard_stats, property=primaries) 1 
crate_node(name=shard_stats, property=replicas) 2
crate_node(name=shard_stats, property=total) 3
crate_node(name=shard_stats, property=unassigned) 0
crate_node(name=shard_stats, property=recovering) 1
crate_node(name=shard_info, property=size, id=1, table=test, partition_ident=p1) 100
crate_node(name=shard_info, property=size, id=2, table=test, partition_ident=p1) 1000
crate_node(name=shard_info, property=size, id=3, table=test, partition_ident=p1) 500
```
> Add shard information to node info metrics

- CHANGES.rst
- src/main/java/io/crate/jmx/recorder/Recorder.java
This makes Recorder ignore unsupported jmx datatypes by default, although they will still be logged. I tested this version with cratedb 4.2, 4.3 and 4.4 and it works.
> Make Recorder ignore unsupported jmx datatypes by default

- README.rst
Remove the version specific (outdated) link to .jar
and replace with version generic link to bintray
> Remove the version specific (outdated) link to .jar

- README.rst
Update wording to reflect that enterprise license is only required for CrateDB < 4.5
> Update wording regarding Enterprise License

- gradle/version.properties
- src/test/java/io/crate/jmx/integrationtests/AbstractITest.java
Iterating over running JVM apps and taking the first one that is named
`CrateDB` is error prone. It could pick-up a foreign CrateDB instance
that was already running on a machine instead of the one spawned by the
test layer.
> Use pid from testCluster server

- gradle/version.properties
For new tarball format handling (Empty folder is no longer first in the
file list)
This will also require a new nightly build with https://github.com/crate/crate/pull/14802
> Update crate_testing to 0.11.1

- src/test/java/io/crate/jmx/integrationtests/AbstractITest.java
Using a static port can cause issues with CI builds.
> Use random HTTP port for integ tests

- src/test/java/io/crate/jmx/integrationtests/AbstractITest.java
Previously, caused `testRequestingMultipleTimesDoesNotResultInDuplicateMetrics`
to fail for the `V570MetricsITest` subclass.
Also, use non-static setup to get open HTTP port, with lazy init,
to match the logic of `testCluster`.
> Shutdown the server after test suite

- build.gradle
Depends on https://github.com/crate/jenkins-dsl/pull/1250
> Use in-memory ascii-armored keys instead of using the gpg agent

- .editorconfig
- CHANGES.rst
- src/main/java/io/crate/jmx/recorder/NodeInfo.java
See https://github.com/crate/crate/pull/16456 for details
```
↪ http localhost:8070 G shard_info
crate_node{name="shard_info",property="size",id="1",schema="s2",table="tbl",partition_ident="",} 0.0
crate_node{name="shard_info",property="size",id="2",schema="s2",table="tbl",partition_ident="",} 0.0
crate_node{name="shard_info",property="size",id="3",schema="s2",table="tbl",partition_ident="",} 0.0
crate_node{name="shard_info",property="size",id="0",schema="s2",table="tbl",partition_ident="",} 208.0
crate_node{name="shard_info",property="size",id="1",schema="s1",table="tbl",partition_ident="",} 0.0
crate_node{name="shard_info",property="size",id="2",schema="s1",table="tbl",partition_ident="",} 0.0
crate_node{name="shard_info",property="size",id="3",schema="s1",table="tbl",partition_ident="", …
```
> Add schema to NodeInfo/ShardInfo

- gradle/version.properties
The package `io.crate:crate-testing` has been released in version 0.12.1, which includes this update:
- https://github.com/crate/crate-java-testing/pull/87
> Dependencies: Update to crate-testing 0.12.1

- CHANGES.rst
- src/main/java/io/crate/jmx/http/HttpMetricHandler.java
Per https://www.ietf.org/rfc/rfc2616.txt:
3.If a Content-Length header field (section 14.13) is present, its
decimal value in OCTETs represents both the entity-length and the
transfer-length. The Content-Length header field MUST NOT be sent
if these two lengths are different (i.e., if a Transfer-Encoding
header field is present). If a message is received with both a
Transfer-Encoding header field and a Content-Length header field,
the latter MUST be ignored.
See also:
- https://docs.oracle.com/en/java/javase/11/docs/api/jdk.httpserver/com/sun/net/httpserver/HttpExchange.html
- https://docs.oracle.com/en/java/javase/11/docs/api/jdk.httpserver/com/sun/net/httpserver/HttpExchange.html#sendResponseHeaders(int,long)
In particular:
getResponseHeaders() to set any response headers, except …
> Don't send both Content-Length and Transfer-Encoding headers

- src/test/java/io/crate/jmx/integrationtests/MetricsITest.java
Following: https://github.com/crate/crate/pull/17678 the `get` thread pool has been removed.
> Remove `get` thread pool from itest

- build.gradle
The OSSRH has reached EOL, new urls must be used to publish the the Maven Central Portal instead.
See https://central.sonatype.org/pages/ossrh-eol/
Removed the publishing.repostiories section as this is not used and needed when using the nexus.publish plugin.
I've verified these changes (was somehow forced too ;) while publishing yesterday's `1.2.1` release.
> Fix sonatype central JAR publishing
